Fixes #211 Check SAME_AS_CONTAINER for container write access
RHEAGROUP/COMET-WebServices-Community-Edition pull request #216
Opened 2021-07-12 10:18 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Check SAME_AS_CONTAINER for container write access

2021-07-12 10:26 UTC, alexatrhea commented
So how do you resolve the container now? Not obvious from the code.

2021-07-12 10:37 UTC, samatrhea requested changes
code looks good, just want to make sure we have 3 edge cases covered:
  - SiteDirectory
  - EngineeringModel
  - Iteration

2021-07-12 10:37 UTC, samatrhea commented on CDP4WebServices.API.Tests/Services/Authorization/PermissionServiceTestFixture.cs
> +        public void VerifySameAsContainerPermissionAutorization()
can you also add tests for:
  - a Thing that is contained by SiteDirectory
  - a Thing that is contained by EngineeringModel
  - a Thing that is contained by Iteration

2021-07-12 12:43 UTC, lxatrhea commented
> 
> 
> So how do you resolve the container now? Not obvious from the code.

The injected `IResolveService` is used for that.

2021-07-13 15:22 UTC, samatrhea approved these changes

2021-07-13 15:58 UTC, alexatrhea approved these changes

2021-07-14 06:57 UTC, merged