ParameterTypeAssignmentCache not being cleared would lead to duplicate keys exception
RHEAGROUP/COMET-WebServices-Community-Edition pull request #260
Opened 2022-04-19 16:03 UTC by alexatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Bug found by OHB. When copying EDs and there is a SFPT in the RDL chain, an exception would get thrown on the server stopping the copy due to cache dictionary not being cleaned up.

2022-04-19 16:10 UTC, samatrhea approved these changes
i am assuming all integration tests work?

2022-04-19 16:25 UTC, alexatrhea commented
> i am assuming all integration tests work?

I don't think there is an integration test dealing with this as this is code you wrote, and we found a bug in.

2022-04-20 04:43 UTC, samatrhea requested changes

2022-04-20 04:43 UTC, samatrhea commented on CDP4WebServices.API/Services/BusinessLogic/Implementation/DefaultValueArrayFactory.cs
> +            this.parameterTypeAssignmentCache.Clear();
in hindsight, i doubt this is the right solution, lets discuss

2022-04-20 06:10 UTC, lxatrhea approved these changes
Don't know why Sam thinks this isn't the right solution. I am probably missing some context.
I don't see any problems about the added row itself.

2022-04-21 15:34 UTC, samatrhea approved these changes
this can be merged, but it may be that the Load method is called too many times

2022-04-22 07:23 UTC, merged