[ADD] Added ThingsChangedMessage producing for post requests
RHEAGROUP/COMET-WebServices-Community-Edition pull request #331
Opened 2024-01-31 15:34 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)
closes #327 
### Description

 Add RaabitMQ to notify a listener of changes to any data in the CDP4-COMET server
  - [x] Add RabbitMQ to message listeners that a change has occured on any kind of Thing. An IThingMessageProducer service needs to be implemented that handles messaging and needs to be injected into the SiteDirectory and EngineeringModel Carter Module POST message handling.
  - [x] add RabbitMQ connection setttings to appsettings.json and include an option to enable/disable messaging
  - [x]  Add RabbitMQ to docker-compose for easy deployment
  - [x] Add a messaging library to the CDP4-COMET-SDK that handles everything around messaging with RabbitMQ, such as the IThingMessageProducer and IThingMessageConsumer services and the defintiion of the message payloads etc.
  - [x] any thing update event, corresponding to a transaction, can contain multiple things that are created updated and deleted. The following data shall be part of an update message. ChangedThings, TimeStamp, AcorID. It must be noted that the 10-25 protocol does not make it explicit that a Thing has been deleted. This is computed by computing the difference between state n and n+1 of the container Thing that contains the Thing that has been deleted

> NOTE: make sure that any calls to the queue are non-blocking and that the CDP4-COMET server is impacted as less as possible (we don't want this to slow us down)
  - [x] Implemented a resolvable background service to queue message to push

2024-01-31 15:55 UTC, lxatrhea requested changes

2024-01-31 15:55 UTC, lxatrhea commented on CometServer/Configuration/ServiceMessagingConfig.cs
> +            this.IsEnabled = true;
I don't think that hard coding stuff here is what we want. Either we have a settings file, or we don;t and then it should just does not work (and log why it doesn't work).

2024-02-01 08:15 UTC, lxatrhea approved these changes

2024-02-01 08:15 UTC, antoineatrhea commented on CometServer.Tests/Configuration/AppConfigServiceTestFixture.cs
> +
Would be nice to wrap all Assert.That by a Assert.Multiple

2024-02-01 08:15 UTC, antoineatrhea commented on CometServer/Configuration/ServiceMessagingConfig.cs
> +            this.IsEnabled = !bool.TryParse(configuration["MessageBroker:IsEnabled"], out var isEnabled) || isEnabled;
you can directly use configuration.GetValue("...", defaultValue:...)

2024-02-01 08:15 UTC, antoineatrhea commented on CometServer/Configuration/ServiceMessagingConfig.cs
> +        public string HostName { get; set; }
Are we sure that would let all properties as public set ? should not be private set?

2024-02-01 16:03 UTC, antoineatrhea approved these changes

2024-02-01 16:05 UTC, merged